version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node@3.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm build
    
workflows:
  tests_and_build:
    jobs:
      - build