version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm build
    
workflows:
  tests_and_build:
    jobs:
      - build